#!/bin/bash

#git add client/client-rest-jersey/src/main/java/eu/europeana/repox/rest/client/accessors/AggregatorsAccessor.java
git add client/client-rest-jersey/src/main/java/eu/europeana/repox/rest/client/accessors/DatasetsAccessor.java
git add client/client-rest-jersey/src/main/java/eu/europeana/repox/rest/client/accessors/HarvestAccessor.java
git add client/client-rest-jersey/src/main/java/eu/europeana/repox/rest/client/accessors/MappingsAccessor.java
git add client/client-rest-jersey/src/main/java/eu/europeana/repox/rest/client/accessors/ProvidersAccessor.java
git add client/client-rest-jersey/src/main/java/eu/europeana/repox/rest/client/accessors/RecordsAccessor.java
git add client/client-rest-jersey/src/main/java/eu/europeana/repox/rest/client/accessors/StatisticsAccessor.java
git add commons/src/main/java/org/oclc/oai/harvester/verb/HarvesterVerb.java
git add commons/src/main/java/pt/utl/ist/marc/iso2709/ISOHandler.java
git add commons/src/main/java/pt/utl/ist/marc/iso2709/ISOHandlerSingleRecord.java
git add commons/src/main/java/pt/utl/ist/marc/iso2709/Iso2709TypeDetector.java
git add commons/src/main/java/pt/utl/ist/marc/iso2709/IsoNavigator.java
git add commons/src/main/java/pt/utl/ist/marc/iso2709/MARCPartialReader.java
git add commons/src/main/java/pt/utl/ist/marc/iso2709/MARCPartialReaderUkraine.java
git add commons/src/main/java/pt/utl/ist/marc/iso2709/MARCReader.java
git add commons/src/main/java/pt/utl/ist/marc/iso2709/Record2Iso2709HorizonVisitor.java
git add commons/src/main/java/pt/utl/ist/marc/xml/DomBuilder.java
git add commons/src/main/java/pt/utl/ist/marc/xml/IteratorMarcXChange.java
git add commons/src/main/java/pt/utl/ist/marc/xml/MarcXChangeBuilder.java
git add commons/src/main/java/pt/utl/ist/marc/xml/MarcXChangeDom4jBuilder.java
git add commons/src/main/java/pt/utl/ist/marc/xml/MarcXChangeXmlBuilder.java
git add commons/src/main/java/pt/utl/ist/recordPackage/RecordRepoxExternalId.java
git add commons/src/main/java/pt/utl/ist/recordPackage/RecordRepoxXpathId.java
git add commons/src/main/java/pt/utl/ist/recordPackage/XmlRecordSplitter.java
git add commons/src/main/java/pt/utl/ist/reports/LogUtil.java
git add commons/src/main/java/pt/utl/ist/util/Dom4jUtil.java
git add commons/src/main/java/pt/utl/ist/util/DomUtil.java
git add commons/src/main/java/pt/utl/ist/util/EmailSender.java
git add commons/src/main/java/pt/utl/ist/util/StringUtil.java
git add commons/src/main/java/pt/utl/ist/util/TarGz.java
git add commons/src/main/java/pt/utl/ist/util/XmlUtil.java
git add commons/src/main/java/pt/utl/ist/util/marc/MarcUtil.java
git add commons/src/main/java/pt/utl/ist/util/marc/RemovePontuationFromAuthorityVisitor.java
git add commons/src/main/java/pt/utl/ist/util/marc/RemovePontuationVisitor.java
git add gui/src/main/java/harvesterUI/client/HarvesterUI.java
git add gui/src/main/java/harvesterUI/server/dataManagement/dataProviders/DataProvidersImportUploadServlet.java
git add gui/src/main/java/harvesterUI/server/dataManagement/dataSets/Z39FileUpload.java
git add gui/src/main/java/harvesterUI/server/harvest/HarvestOperationsServiceImpl.java
git add gui/src/main/java/harvesterUI/server/projects/DefaultSaveData.java
git add gui/src/main/java/harvesterUI/server/transformations/TransformationFileUpload.java
git add gui/src/main/java/harvesterUI/server/util/Util.java
git add manager/pom.xml
git add manager/src/main/java/pt/utl/ist/accessPoint/RecordRepoxFullAccessPoint.java
git add manager/src/main/java/pt/utl/ist/accessPoint/manager/DefaultAccessPointsManager.java
git add manager/src/main/java/pt/utl/ist/accessPoint/manager/SqlAccessPointsManager.java
git add manager/src/main/java/pt/utl/ist/configuration/DefaultRepoxContextUtil.java
git add manager/src/main/java/pt/utl/ist/configuration/DefaultRepoxManager.java
git add manager/src/main/java/pt/utl/ist/dataProvider/Aggregator.java
git add manager/src/main/java/pt/utl/ist/dataProvider/Countries.java
git add manager/src/main/java/pt/utl/ist/dataProvider/DataSource.java
git add manager/src/main/java/pt/utl/ist/dataProvider/DefaultDataManager.java
git add manager/src/main/java/pt/utl/ist/dataProvider/dataSource/DataSourceTester.java
git add manager/src/main/java/pt/utl/ist/dataProvider/dataSource/DataSourcesMonitor.java
git add manager/src/main/java/pt/utl/ist/dataProvider/dataSource/IdExtractedRecordIdPolicy.java
git add manager/src/main/java/pt/utl/ist/dataProvider/dataSource/IdGeneratedRecordIdPolicy.java
git add manager/src/main/java/pt/utl/ist/dataProvider/dataSource/SimpleFileExtractStrategy.java
git add manager/src/main/java/pt/utl/ist/dataProvider/dataSource/TagsManager.java
git add manager/src/main/java/pt/utl/ist/database/DerbyDatabaseAccess.java
git add manager/src/main/java/pt/utl/ist/database/MysqlDatabaseAccess.java
git add manager/src/main/java/pt/utl/ist/database/PostgresqlDatabaseAccess.java
git add manager/src/main/java/pt/utl/ist/externalServices/ExternalNoMonitorServiceThread.java
git add manager/src/main/java/pt/utl/ist/externalServices/ExternalRestService.java
git add manager/src/main/java/pt/utl/ist/externalServices/ExternalRestServiceThread.java
git add manager/src/main/java/pt/utl/ist/externalServices/ExternalRestServicesManager.java
git add manager/src/main/java/pt/utl/ist/externalServices/ServiceParameter.java
git add manager/src/main/java/pt/utl/ist/ftp/FtpFileRetrieveStrategy.java
git add manager/src/main/java/pt/utl/ist/http/HttpFileRetrieveStrategy.java
git add manager/src/main/java/pt/utl/ist/ldap/LDAPAuthenticator.java
git add manager/src/main/java/pt/utl/ist/marc/DirectoryImporterDataSource.java
git add manager/src/main/java/pt/utl/ist/marc/Iso2709FileExtractStrategy.java
git add manager/src/main/java/pt/utl/ist/marc/MarcXchangeFileExtractStrategy.java
git add manager/src/main/java/pt/utl/ist/marc/RecordRepoxMarc.java
git add manager/src/main/java/pt/utl/ist/metadataSchemas/MetadataSchemaManager.java
git add manager/src/main/java/pt/utl/ist/metadataTransformation/MetadataTransformation.java
git add manager/src/main/java/pt/utl/ist/metadataTransformation/MetadataTransformationManager.java
git add manager/src/main/java/pt/utl/ist/oai/OaiDataSource.java
git add manager/src/main/java/pt/utl/ist/oai/OaiHarvester.java
git add manager/src/main/java/pt/utl/ist/oai/ResponseTransformer.java
git add manager/src/main/java/pt/utl/ist/rest/statistics/DefaultStatisticsManager.java
git add manager/src/main/java/pt/utl/ist/statistics/DefaultStatisticsManager.java
git add manager/src/main/java/pt/utl/ist/statistics/RecordCountManager.java
git add manager/src/main/java/pt/utl/ist/task/ExportToFilesystem.java
git add manager/src/main/java/pt/utl/ist/task/IngestDataSource.java
git add manager/src/main/java/pt/utl/ist/task/OldTaskReviewer.java
git add manager/src/main/java/pt/utl/ist/task/Task.java
git add manager/src/main/java/pt/utl/ist/task/TaskFileHelper.java
git add manager/src/main/java/pt/utl/ist/task/TaskManager.java
git add manager/src/main/java/pt/utl/ist/z3950/AbstractHarvester.java
git add manager/src/main/java/pt/utl/ist/z3950/DataSourceZ3950.java
git add manager/src/main/java/pt/utl/ist/z3950/IdListHarvester.java
git add manager/src/main/java/pt/utl/ist/z3950/IdSequenceHarvester.java
git add manager/src/main/java/pt/utl/ist/z3950/Target.java
git add manager/src/main/java/pt/utl/ist/z3950/TimestampHarvester.java
git add pom.xml
git add server/oai/src/main/java/org/oclc/oai/server/catalog/NodeRecordFactory.java
git add server/oai/src/main/java/org/oclc/oai/server/catalog/helpers/RecordStringHandler.java
git add server/oai/src/main/java/org/oclc/oai/server/crosswalk/NodePassThruCrosswalk.java
git add server/oai/src/main/java/pt/utl/ist/oai/server/catalog/DataSourceOaiCatalog.java
git add server/rest/src/main/java/pt/utl/ist/rest/RestServlet.java
git add server/rest/src/main/java/pt/utl/ist/rest/services/web/DefaultWebServices.java
git add server/rest/src/main/java/pt/utl/ist/rest/services/web/rest/RestUtils.java
